### ISSUE TITLE
Fix 'Run in Tray'

### ISSUE THREAD

**Issue by MaterialFoundry** [MaterialFoundry/MaterialCompanion#3]

**Comment by coffiarts** [comment]
Having this issue myself, so I'll do my best to provide a description:

I am on Windows 10.

MC works fine, apart from this detail: 
![image](https://github.com/MaterialFoundry/MaterialCompanion/assets/39616483/3872172f-0850-48d3-aa58-f2bc32b7ff2f)

- Click "Run in tray" and then "Save".
- This closes the window, then ropens it automatically.
- MC still running fine, but still in window mode (obviously)
- Close the window => shuts down MC completely (there's no tray icon)

Anyone apart from me able to reproduce that?
Am I missing something?

Thanks a lot for looking into this!

**Comment by selflogic** [comment]
I confirm I have the same issue.  
Material Companion Version 1.0.2 
Windows 10 Version 22H2

This is an ugly hack but it meets my needs so far, I just found it.  I just thought I'd add it, that it may help some people before an official patch is created.  I don't know anything about the creator.  I just know it's working for me.
https://github.com/sandwichdoge/MinimizeToTray

**Comment by be221b** [comment]
Same issue
