### ISSUE TITLE
Antivirus-System is finding a Trojan

### ISSUE THREAD

**Issue by Gabbaoma** [MaterialFoundry/MaterialCompanion#7]
Hi, Bitdefender is finding a Trojan.Generic.KD.70692313 in the pymcuprog.exe. See image below.
![image](https://github.com/MaterialFoundry/MaterialCompanion/assets/97093071/048fc0f6-3dea-40c7-b65e-b3e899be8d7c)

**Comment by stillday** [comment]
i get the same warning

**Comment by Gabbaoma** [comment]
1.03 works. Thanks!
