### ISSUE TITLE
Material Companion is not detecting Stream Deck

### ISSUE THREAD

**Issue by jofrepouplana** [MaterialFoundry/MaterialCompanion#9]
Material Companion is not detecting Stream Deck Mini...
Stream Deck is actualized 6.5.1 Firmware 3.02.001
Foundry v11 Build 315 Module Material Deck 1.6.2

![material companion](https://github.com/MaterialFoundry/MaterialCompanion/assets/26244801/51fac72a-3328-4292-91bd-ad8d3783acb7)
![Stream Deck Mini](https://github.com/MaterialFoundry/MaterialCompanion/assets/26244801/720a97ed-88a9-4756-82d2-1ce923e33dfc)

**Comment by MaterialFoundry** [comment]
Is the Stream Deck application running and did you install the Stream Deck plugin (see [here](https://github.com/MaterialFoundry/MaterialDeck/wiki/Installation#installing-the-stream-deck-plugin))?

**Comment by jofrepouplana** [comment]
Thank you! Now it works.

**Comment by jofrepouplana** [comment]
.
